### ISSUE TITLE
Question 1.3.7

### ISSUE THREAD

**Issue by fredthedead** [Edderic/causal-inference-in-statistics-solutions#1]
Hey Edderic,
Thanks for posting your solutions, I'm going through the book now too and trying to solve the study questions - it's very helpful to have a reference to compare to.

Regarding question 1.3.7.a -  you've answered that P(y|x)=0 however if we know that "at least one coin lands on head" (=x) doesn't that mean that the probability that both have landed on head (=y) is now higher? my answer was that there are 3 scenarios where 'x' is 'true' - 'h-t', 't-h', 'h-h', and out of these only 1 will make 'y' true too, so P(y|x)=0.333) (if that's right then the answers to the followup questions will change too)

Looking forward for you solutions to the other chapters.
If you would rather not get comments on the solutions, feel free to let me know

Fred

**Comment by Edderic** [comment]
Hey FredTheDead,

Glad it's helpful! Thank you for pointing out the error! I incorrectly read the problem -- I read "Player 2 receives a dollar if and only if the two coins land on the same face" as "Player 2 receives a dollar if and only if two coins lands as tails." I made the changes and also ran a simulation to verify that answers are now correct. Whoops! 

I finished Chapter 2 but still need to type it up. I will be posting it soon :)

Please let me know if you find other errors. Thank you!
